spring:
  h2:
    console:
      enabled: true
      path: "/h2-console"
  datasource:
    url: "jdbc:h2:mem:tasklist"
    driverClassName: "org.h2.Driver"
    username: "sa"
    password: ""
  thymeleaf:
    cache: false


